### ISSUE TITLE
ArchGDAL Polygons are drawn with `mesh` instead of `poly` in CairoMakie

### ISSUE THREAD

**Issue by henrik-wolf** [JuliaGeo/GeoInterface.jl#104]
The recipes specified in `GeoInterfaceMakie` seem to cause a call to the `mesh` method, rather than the `poly` method, as might be intended. When first converting to a basic geometry with `GeoInterfaceMakie.basicsgeom`, everything works as expected.

MWE:
```julia
using ArchGDAL
using CairoMakie
using GeoInterfaceMakie

GeoInterfaceMakie.@enable ArchGDAL.IGeometry

gdal_poly = ArchGDAL.fromWKT("POLYGON ((183.492422450854 -1185.41280664137,197.369193532101 -1193.21088348219,202.631564992947 -1183.84648028715,204.428192938311 -1184.85610096959,208.12543886477 -1186.93376090569,206.928258602903 -1189.06415687995,197.560983313468 -1205.73336047844,197.073028343411 -1206.60157731585,194.040318792817 -1204.89733601772,178.555501755156 -1196.19557220825,170.582765260926 -1191.71524920661,176.372704238476 -1181.41193586764,183.1674535579 -1185.23024863862,183.492422450854 -1185.41280664137))")
basic_poly = GeoInterfaceMakie.basicsgeom(gdal_poly)
begin
    fig = Figure(resolution=(1000, 400))
    ax1 = Axis(fig[1, 1], autolimitaspect=1.0, title="ArchGDAL polygon")
    ax2 = Axis(fig[1, 2], autolimitaspect=1.0, title="Basic geometry polygon")
    poly!(ax1, gdal_poly, color=(:red, 0.4))
    poly!(ax2, basic_poly, color=(:green, 0.4))
    fig
end
```
produces:
![plot_25](https://github.com/JuliaGeo/GeoInterface.jl/assets/49985053/a935353d-89cc-455e-97e5-fa1d18182263)

This feels very similar to MakieOrg/Makie.jl#2469, therefore might even be an issue to raise with makie itself... Any ideas?

**Comment by visr** [comment]
This is quite curious. Indeed this looks similar to https://github.com/MakieOrg/Makie.jl/issues/2469. Also works fine in GLMakie, and I don't see anything related to mesh in this package.

From https://github.com/MakieOrg/Makie.jl/issues/2469#issuecomment-1337512370

> The fix here is to make this kind of polygon not hit the mesh drawing routines, something in the dispatch setup must miss it. Maybe because the input argument is a Circle and not a Poly.

@jkrumbiegel do you suspect this is the same general problem, and perhaps have an idea of how this could be fixed?

GeoInterfaceMakie is quite small: https://github.com/JuliaGeo/GeoInterface.jl/blob/main/GeoInterfaceMakie/src/GeoInterfaceMakie.jl

**Comment by jkrumbiegel** [comment]
I'll have to take a look, I suspect there might be a more intelligent way to intercept the polygons in CairoMakie so they don't fall back to meshes, but also such that I don't have to specify every single possible type and color combination there is.

**Comment by asinghvi17** [comment]
This still seems to be an issue today, unfortunately.  Updated example here:
```julia
using ArchGDAL
using CairoMakie
using GeoInterfaceMakie

GeoInterfaceMakie.@enable ArchGDAL.IGeometry

gdal_poly = ArchGDAL.fromWKT("POLYGON ((183.492422450854 -1185.41280664137,197.369193532101 -1193.21088348219,202.631564992947 -1183.84648028715,204.428192938311 -1184.85610096959,208.12543886477 -1186.93376090569,206.928258602903 -1189.06415687995,197.560983313468 -1205.73336047844,197.073028343411 -1206.60157731585,194.040318792817 -1204.89733601772,178.555501755156 -1196.19557220825,170.582765260926 -1191.71524920661,176.372704238476 -1181.41193586764,183.1674535579 -1185.23024863862,183.492422450854 -1185.41280664137))")
basic_poly = GeoInterfaceMakie.GeoInterface.convert(Makie.GeometryBasics, gdal_poly)
begin
    fig = Figure(size=(1000, 400))
    ax1 = Axis(fig[1, 1], autolimitaspect=1.0, title="ArchGDAL polygon")
    ax2 = Axis(fig[1, 2], autolimitaspect=1.0, title="Basic geometry polygon")
    poly!(ax1, gdal_poly, color=(:red, 0.4))
    poly!(ax2, basic_poly, color=(:green, 0.4))
    fig
end
```
![iTerm2 TxubcF](https://github.com/JuliaGeo/GeoInterface.jl/assets/32143268/aa69606d-d564-47b1-97f0-b3b61169a5f2)

**Comment by asinghvi17** [comment]
Not an issue anymore!

![iTerm2 AG3BaV](https://github.com/JuliaGeo/GeoInterface.jl/assets/32143268/9ba63554-8f84-42c1-902d-fb0532df8c54)
