### ISSUE TITLE
Support latest Makie

### ISSUE THREAD

**Issue by justinmimbs** [JuliaGeo/GeoInterface.jl#113]
MakieCore is now at v0.7, and it would be nice to use GeoInterfaceMakie with the latest Makie.

```
(jl_HEdmHk) pkg> add MakieCore GeoInterfaceMakie
   Resolving package versions...

(jl_HEdmHk) pkg> status --outdated 
Status `/tmp/jl_HEdmHk/Project.toml`
⌅ [20f20a25] MakieCore v0.6.9 (<v0.7.0): GeoInterfaceMakie
```

**Comment by rafaqz** [comment]
PRs always help, imagine how many other packages the maintainers here also have to do this for ;)

**Comment by justinmimbs** [comment]
Update: I thought this might be as simple as adding MakieCore 0.7.0 to the compat, but it wasn't so. 😅 When I did that and ran tests, the tests errored. After digging a little, it seems that the latest Makie throws when trying to `plot!(ax, ...)`, even with simple args.
- https://github.com/MakieOrg/Makie.jl/issues/3399

**Comment by rafaqz** [comment]
Thanks, maybe there was a breaking syntax change?

But yes, it may not just be about bumping the version. If you have time to see it through to completion that would be a huge help.

**Comment by justinmimbs** [comment]
From what I can tell, it doesn't look like any of the breaking changes should affect the code in GeoInterfaceMakie. I can reproduce the error with code straight from Makie tests, so I do wonder if I'm missing something.

And sure thing, I'll try to follow through on this.

**Comment by justinmimbs** [comment]
Simon has opened a PR for the compat update (it would need a version bump for release), and I can confirm this works with Makie 0.20.1. (Thanks for the quick fix @SimonDanisch.)
