### ISSUE TITLE
MultiLineString() throws UndefVarError: line not defined

### ISSUE THREAD

**Issue by cchderrick** [JuliaGeo/GeoInterface.jl#17]
Should be `MultiLineString(coordinates(lines))` instead of `MultiLineString(coordinates(line))`
https://github.com/JuliaGeo/GeoInterface.jl/blob/02bb014ff6a05b3a4d2c4dbfe3a8059ea9daf327/src/geotypes.jl#L80

**Comment by visr** [comment]
Oh yes good catch, thanks! Feel free to directly create a PR if the mistake is clear like here.

**Comment by visr** [comment]
Fixed by #18
