### ISSUE TITLE
coordinates return a Vector of Vector

### ISSUE THREAD

**Issue by mkborregaard** [JuliaGeo/GeoInterface.jl#20]
Why not return a Vector of Tuples? Given that points are  immutable. Tuples are stack allocated and much faster.

**Comment by yeesian** [comment]
How might we handle [jagged arrays](https://en.wikipedia.org/wiki/Jagged_array) using a Vector of Tuples?

**Comment by mkborregaard** [comment]
I might be misunderstanding the spec, but I meant each 2d or 3d point to be represented by a Tuple (the innermost Array) - the outer ones can have variable length and should be arrays. Or am I getting this wrong?

**Comment by yeesian** [comment]
Yes, that should be possible. I just kept it to vectors for simplicity of implementation to get something going.

**Comment by mkborregaard** [comment]
I'll try to see if I can work this out, but it looks like the whole interface expects Vectors at the lowest level, so this would need changing lots of places, right?

**Comment by juliohm** [comment]
I suggest to use a StaticArrays.jl instead like I do in GeoStats.jl. Every coordinate is stack-allocated and still works in the context of linear algebra calculations. Basically a tuple on steroids.

**Comment by mkborregaard** [comment]
That is another option - or perhaps even better using GeometryTypes.Point which is just a StaticArray.
It's just a question of that I don't know exactly what the intention is here - Tuples are the most assumption-free. What do you use linear algebra for on Points?

But definitely, I think a common abstraction for Points in Julia would be great. See also https://github.com/JuliaPlots/Plots.jl/issues/1886#issuecomment-454948882

**Comment by mkborregaard** [comment]
Why traits and not just using the same type? Nothing is simpler than Point.
@yeesian no I did try to change that line, but the implementation in Shapefile/geo_interface.jl does not use the GeoInterface interface! It reimplements coordinates as Vectors.

**Comment by yeesian** [comment]
> Why traits and not just using the same type? Nothing is simpler than Point.

There's https://github.com/JuliaGeometry/meta/wiki/First-Meetup and https://github.com/JuliaGeometry/meta/wiki/First-Meetup-Minutes

> the implementation in Shapefile/geo_interface.jl does not use the GeoInterface interface! It reimplements coordinates as Vectors.

Yup, that's the only hard part about it, no? Changing what an interface expects should be easy. What is more tedious is updating all the packages that implements it.

**Comment by juliohm** [comment]
I think that by using StaticArrays.jl, which is quite standard nowadays, we gain a lot of functionality for free. Reimplementing all the same operations for Point or any other type wouldn't be productive. A generic traits-based interface also sounds like a good path forward.

I think the crux here is to keep in mind that points are just "vectors" and that people will definitely make linear algebra calculations with them.

**Comment by maxfreu** [comment]
Have you made a decision on this?

**Comment by visr** [comment]
Yes, it's going to be the number 2 above, see also #33, #26. There is no 'blessed' type like mentioned under number 1, but we try to encourage using the types from GeometryBasics if possible.

**Comment by evetion** [comment]
Closed by the traits interface of #33.
