### ISSUE TITLE
FR: Use GeometryTypes points instead of custom ones

### ISSUE THREAD

**Issue by asinghvi17** [JuliaGeo/GeoInterface.jl#24]
Would make interop a lot easier, especially with Makie et al which use GeometryTypes.

**Comment by rafaqz** [comment]
And everything else!

https://github.com/JuliaGeometry/GeometryTypes.jl/pull/166

Seems like the long term plan...

**Comment by visr** [comment]
@asinghvi17 what do you think about taking it this direction: https://github.com/JuliaGeo/GeoJSON.jl/issues/21 (and linked discussions)?

**Comment by evetion** [comment]
GeoInterface now implements traits, so we don't depend on other packages like GeometryTypes.
