### ISSUE TITLE
GeoInterface v1.0 RFC

### ISSUE THREAD

**Issue by visr** [JuliaGeo/GeoInterface.jl#26]
@yeesian and I have already done some prototyping on what we would want GeoInterface v1.0 to look like.

See https://github.com/yeesian/GeoInterfaceRFC.jl. I'm making this issue mainly to have a link to the RFC. The RFC is probably best discussed there. Once finished, we probably want to move the new code here. But for that we would appreciate a lot of input, to make sure we get this right and can offer a GeoInterface that works for a wide variety of use cases.

This would address for instance #20 and #23.

**Comment by evetion** [comment]
Closed by concrete implementation of #33
