### ISSUE TITLE
Points as AbstractPositions

### ISSUE THREAD

**Issue by elinder912** [JuliaGeo/GeoInterface.jl#35]
I am having trouble getting hasz() to work on points as I would expect.
julia> using GeoInterface

julia> p = Point([1.0, 2.0])
Point([1.0, 2.0])

julia> p isa Point
true

julia> p isa Position
false

julia> p isa AbstractPosition
false

julia> hasz(p)
ERROR: MethodError: no method matching hasz(::Point)
Closest candidates are:
  hasz(::Array{Float64,1}) at /Users/eric/.julia/packages/GeoInterface/3wxw3/src/geotypes.jl:23
  hasz(::AbstractPosition) at /Users/eric/.julia/packages/GeoInterface/3wxw3/src/GeoInterface.jl:31
Stacktrace:
 [1] top-level scope at REPL[14]:1

**Comment by visr** [comment]
Ah, yes, as you saw this function is not defined for Point, but for positions. If you call hasz on `coordinates(p)` it should work.
