### ISSUE TITLE
Union(args...) is depricated

### ISSUE THREAD

**Issue by OmriRoames** [JuliaGeo/GeoInterface.jl#5]
Needs to be replaced with Union{args...}

**Comment by OmriRoames** [comment]
Sorry, I didn't realize it was already fixed

**Comment by yeesian** [comment]
Not at all; it's my fault for not tagging METADATA. If you'd like, can you help update METADATA for both this package, and LibGEOS?

**Comment by OmriRoames** [comment]
I would love but I'm afraid I don't know how :( I'm very new to Julia and know very little about packaging etc

**Comment by yeesian** [comment]
Thanks! I'll do the following:

1. Read the manual on [tagging packages](http://docs.julialang.org/en/latest/manual/packages/#tagging-and-publishing-your-package)
2. Check out `master` of the package you'd like to tag, before running `Pkg.tag("PackageToBeTagged")` in a julia session. This will update `PackageToBeTagged/` in your `~/.julia/v0.4/METADATA/` folder.
3. Open a PR at [METADATA.jl](https://github.com/JuliaLang/METADATA.jl) with the changes in (2). You can see previous PRs (e.g. https://github.com/JuliaLang/METADATA.jl/commit/72e60364d460d9c82e1c18c86751d844a5ec94a8) for examples of what it should look like.

Let me know if there's anything I can help to clarify.
