### ISSUE TITLE
Fallback point implementations

### ISSUE THREAD

**Issue by visr** [JuliaGeo/GeoInterface.jl#54]
Currently nothing from Base is a geometry by default, in the way that in Tables.jl a Vector of NamedTuple or NamedTuple of Vector is a table. Would it made sense to support some? It might be nice if e.g. a SVector or NTuple would be considered a point.

It looks like it would only take:

```julia
GeoInterface.isgeometry(::AbstractVector{<:Real}) = true
GeoInterface.geomtype(::AbstractVector{<:Real}) = PointTrait()
GeoInterface.ncoord(::PointTrait, geom::AbstractVector{<:Real}) = length(geom)
GeoInterface.getcoord(::PointTrait, geom::AbstractVector{<:Real}, i) = getindex(geom, i)

GeoInterface.isgeometry(::NTuple{N, <:Real}) where {N} = true
GeoInterface.geomtype(::NTuple{N, <:Real}) where {N} = PointTrait()
GeoInterface.ncoord(::PointTrait, geom::NTuple{N, <:Real}) where {N} = N
GeoInterface.getcoord(::PointTrait, geom::NTuple{N, <:Real}, i) where {N} = getindex(geom, i)
```

Perhaps we could even do this for AbstractVector of AbstractVector, e.g. the old GeoInterface concrete GeoJSON based types would still fall under the new interface.

https://github.com/JuliaGeo/Proj4.jl/pull/64

**Comment by evetion** [comment]
I can see the case for a `NTuple` to be Pointlike. Maybe a `NamedTuple` with `:X` and `:Y` as well? In the same sense, SVector would work as well, because it's sized. Any unsized iterators become vague, as it could as easily be a `MultiPoint` or even flattened geometries.

**Comment by visr** [comment]
> Maybe a NamedTuple with :X and :Y as well?

Sure, why not. Then you can also do Z and M. Any particular reason you went with capitalized axis names by the way? Is that SF?

> Any unsized iterators become vague

I see how there could be cases where this fallback would not apply, but users can always add methods to deal with those. The benefit of having the fallback IMO outweighs this. E.g. all the FugroRoames code of Chris and Andy treats `AbstractVector{<:Real}` as points.

**Comment by rafaqz** [comment]
This makes sense to me. Definately for tuples and  xyz zxy etc `NamedTuple` as well. StaticArrays are also a sensible point type, but its unlikely to get  GeoInterface dep. So `AbstractVector` might be the best we can get - although I agree it a bit vague.
