### ISSUE TITLE
[FR] Support Proj.jl transformations on arbitrary geometries

### ISSUE THREAD

**Issue by piever** [JuliaGeo/GeoInterface.jl#62]
As discussed on slack, I imagine it should be possible to write a utility that takes as input a [Proj.jl](https://github.com/JuliaGeo/Proj.jl) transformation and a complex GeoInterface-compliant geometry (for example a polygon or multipolygon), and returns a transformed GeoInterface-compliant geometry (in this case, a new polygon with transformed points).

I'm not sure what's the best place for such a utility to live, maybe Proj.jl itself could take GeoInterface as a dependency and generalize the transformation from points to arbitrary geometries.

**Comment by asinghvi17** [comment]
Now that GeoInterface has the ability to convert back and forth between package geometry implementations, can we introduce a `GeoInterface.transform` function, which can be overloaded by a pacakge, but has the default behaviour of:

- decomposing to tuples-as-points
- transforming using Proj 
- going back up by construction 

This flow might look something like (polygon -> linestring -> point -> transform -> transformed-point -> transformed-linestring -> transformed-polygon)

I have utilities which do this for GeometryBasics but would love to have those live in either Proj or GeoInterface.

**Comment by rafaqz** [comment]
Another option would be to make a lazy representation of the geometries over a vector of points, as you destructure them?

I'm not sure we need to convert back to the package types eagerly, they can also just accept GeoInterface.jl geometries in their methods, and should do that anyway.

**Comment by evetion** [comment]
We could also introduce GeoInterface.map, which would apply any function to the inner coordinates. You could pass a Proj.Transformation to solve this issue and it wouldn't require any changes to Proj.

Only downside would be that there could be optimisations for passing a list of coordinates instead of single coordinate. Maybe that's something to solve with a kw like flatten.

**Comment by asinghvi17** [comment]
For anyone looking at this issue: we have something for this in https://github.com.asinghvi17/GeometryOps.jl - which should get its first release at some point before JuliaCon 2024

**Comment by asinghvi17** [comment]
This is now implemented as an extension in GeometryOps.
