### ISSUE TITLE
Automatic conversion between geometry types

### ISSUE THREAD

**Issue by evetion** [JuliaGeo/GeoInterface.jl#73]
On Slack, @jaakkor2 provided this:

```julia
import GeoJSON, LibGEOS
a = """{"type": "FeatureCollection", "features": [
    {"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[0.0, 0.0], [1.0, 0.0], [0.0, 1.0], [0.0, 0.0]]]}}
    ]}"""
poly1 = GeoJSON.read(a)[1].geometry
LibGEOS.area(poly1)    # fails
```

Note the assumption that geometries "just work" without conversion. Is that something we could do better? Means mostly that we don't just provide a `convert`, but also to automatically take the correct type to convert into. A `GeoJSON.Polygon` becomes a `LibGEOS.Polygon` automatically.

**Comment by rafaqz** [comment]
It would be nice if that did just work... we need to make sure `convert` works everywhere I guess.

**Comment by rafaqz** [comment]
But I guess if you are trying to run `area` specifically with `LibGeos` you will need to use `LigGeos.area`?

The GeoInterface.jl method will try to use the package matching the object type? I'm not actually sure how and where these implementations are. How do we deal with dispatch for those?

**Comment by yeesian** [comment]
I think the (burden of the) work will be in the individual packages to implement their methods for GeoInterface types/traits.

**Comment by rafaqz** [comment]
Note that I've implemented this for ArchGDAL and LibGEOS, it's just waiting on the wrapper types PR for testing.
https://github.com/JuliaGeo/LibGEOS.jl/pull/156
https://github.com/yeesian/ArchGDAL.jl/pull/366

It's surprisingly easy to implement.

**Comment by rafaqz** [comment]
The LibGEOS example works now
