### ISSUE TITLE
Makie plotting LibGEOS MultiLineString shows additional lines

### ISSUE THREAD

**Issue by jaakkor2** [JuliaGeo/GeoInterface.jl#83]
```
using GLMakie, GeoInterfaceMakie, LibGEOS
GeoInterfaceMakie.@enable(LibGEOS.AbstractGeometry)
mls = readgeom("MULTILINESTRING ((0 0,3 0,3 3,0 3,0 0),(1 1,2 1,2 2,1 2,1 1))")
plot(mls)
```
results in with extra line (0,0)->(1,1)
![image](https://user-images.githubusercontent.com/7318249/208681133-a1a63818-230e-434e-a7ef-89eb76db24d0.png)

This in Makie
```
lines([0,3,3,0,0,NaN,1,2,2,1,1],[0,0,3,3,0,NaN,1,1,2,2,1])
```
gives the expected output
![image](https://user-images.githubusercontent.com/7318249/208681597-94515c75-ecb9-4c45-8409-c3cadc28b2bd.png)

**Comment by rafaqz** [comment]
Any ideas about this @jw3126 ?

**Comment by jw3126** [comment]
What happens internally is that we convert to a `GeometryBasics.MultiLineString` https://github.com/JuliaGeo/GeoInterface.jl/blob/827af7c217370281a6d940dae2c84bf2f2f95dca/GeoInterfaceMakie/src/GeoInterfaceMakie.jl#L52
and than plot that. So I think what should be checked is that:
* Does GeometryBasics.MultiLineString plot as expected?
* Does the conversion work as expected?
I don't have the bandwidth to do this right now myself, if you want to give it a shot @jaakkor2 that would be awesome.

**Comment by jaakkor2** [comment]
This works
```
using GLMakie, Makie.GeometryBasics
linestring1 = LineString(Point{2, Int}[(0, 0), (3, 0), (3, 3), (0, 3), (0, 0)])
linestring2 = LineString(Point{2, Int}[(1, 1), (2, 1), (2, 2), (1, 2), (1, 1)])
multilinestring = MultiLineString([linestring1, linestring2])
plot(multilinestring)
```
and this works as well
```
using GLMakie, GeoInterfaceMakie, LibGEOS
mls = readgeom("MULTILINESTRING ((0 0,3 0,3 3,0 3,0 0),(1 1,2 1,2 2,1 2,1 1))")
plot(GeoInterfaceMakie.basicsgeom(mls))
```
So looks like it is not hitting the correct conversion.

**Comment by jw3126** [comment]
Thanks @jaakkor2 . I think it hits https://github.com/JuliaGeo/GeoInterface.jl/blob/827af7c217370281a6d940dae2c84bf2f2f95dca/GeoInterfaceMakie/src/GeoInterfaceMakie.jl#L69

For e.g. scatter this would be correct, but for lines, all Multi geometries will get messed up. So we need to intercept 
multi geometries for lines.
