### ISSUE TITLE
x y z exports

### ISSUE THREAD

**Issue by visr** [JuliaGeo/GeoInterface.jl#9]
Though convenient, I'm not sure we should export the single letter functions `x`, `y` and `z`, since they are commonly used as variable names.
A possible alternative is `xcoord`, `ycoord` and `zcoord`, like is used [here](https://github.com/visr/LasIO.jl/blob/32e42592b25c0e807995c9fb997feaee020a2dac/test/runtests.jl#L20).

**Comment by yeesian** [comment]
Sure, I'll be on-board with that.
